// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file submodules/protobuf/greet/v1/greet.proto (package greet.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file submodules/protobuf/greet/v1/greet.proto.
 */
export const file_submodules_protobuf_greet_v1_greet: GenFile = /*@__PURE__*/
  fileDesc("CihzdWJtb2R1bGVzL3Byb3RvYnVmL2dyZWV0L3YxL2dyZWV0LnByb3RvEghncmVldC52MSIcCgxHcmVldFJlcXVlc3QSDAoEbmFtZRgBIAEoCSIhCg1HcmVldFJlc3BvbnNlEhAKCGdyZWV0aW5nGAEgASgJMkoKDEdyZWV0U2VydmljZRI6CgVHcmVldBIWLmdyZWV0LnYxLkdyZWV0UmVxdWVzdBoXLmdyZWV0LnYxLkdyZWV0UmVzcG9uc2UiAEJXWlVnaXRodWIuY29tL2Nsb2NrLWVuL2Nvbm5lY3Qtc2FtcGxlLWJhY2tlbmQvcGJnZW4vc3VibW9kdWxlcy9wcm90b2J1Zi9ncmVldC92MTtncmVldHYxYgZwcm90bzM");

/**
 * @generated from message greet.v1.GreetRequest
 */
export type GreetRequest = Message<"greet.v1.GreetRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greet.v1.GreetRequest.
 * Use `create(GreetRequestSchema)` to create a new message.
 */
export const GreetRequestSchema: GenMessage<GreetRequest> = /*@__PURE__*/
  messageDesc(file_submodules_protobuf_greet_v1_greet, 0);

/**
 * @generated from message greet.v1.GreetResponse
 */
export type GreetResponse = Message<"greet.v1.GreetResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message greet.v1.GreetResponse.
 * Use `create(GreetResponseSchema)` to create a new message.
 */
export const GreetResponseSchema: GenMessage<GreetResponse> = /*@__PURE__*/
  messageDesc(file_submodules_protobuf_greet_v1_greet, 1);

/**
 * @generated from service greet.v1.GreetService
 */
export const GreetService: GenService<{
  /**
   * @generated from rpc greet.v1.GreetService.Greet
   */
  greet: {
    methodKind: "unary";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_submodules_protobuf_greet_v1_greet, 0);

